name: Feature request
description: An idea to make the honeypot better
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to detect or do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How could it work?
